#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

##############################################################################
echo "=== disk-usage Level 1 ==="
sudo du -xh --exclude=/proc --max-depth=1 / | sort -hr

echo "=== Deleting un-needed framework/tool dirs ==="

rm -rf /usr/local/.ghcup # haskell installer: ~6.4GB
rm -rf /usr/share/dotnet # dotnet: ~4GB
rm -rf /usr/share/swift # swift: ~3.2GB
rm -rf /usr/lib/jvm # jvm: ~1.5GB


echo "=== Github Workspace Usage for $GITHUB_WORKSPACE ==="
du -h --max-depth=1 "$GITHUB_WORKSPACE" | sort -hr

echo "=== Running cluster-autoscaler unit-tests..."

cd cluster-autoscaler
go test $(go list ./... | grep -v cloudprovider | grep -v integration)
go test $(go list ./cloudprovider/mcm/...)

#TODO: Return success failure properly
echo "CI tests are done"
