#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

##############################################################################
echo "=== disk-usage Level 1 ==="
sudo du -xh --max-depth=1 / | sort -hr

echo ""
echo "=== disk-usage Level 2 ==="
LARGEST=$(sudo du -xh --exclude=/proc  --max-depth=1 / | sort -hr | head -5 | awk '{print $2}')
for d in $LARGEST; do
  echo ""
  echo "--- $d ---"
  sudo du -xh --exclude=/proc --max-depth=1 "$d" | sort -hr
done

echo "=== Github Workspace Usage for $GITHUB_WORKSPACE ==="
du -h --max-depth=1 "$GITHUB_WORKSPACE" | sort -hr

echo "=== Running cluster-autoscaler unit-tests..."

cd cluster-autoscaler
go test $(go list ./... | grep -v cloudprovider | grep -v integration)
go test $(go list ./cloudprovider/mcm/...)

#TODO: Return success failure properly
echo "CI tests are done"
